[package]
name = "aoc2025"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
itertools = "0.13.0"
num = "0.4.3"
bytemuck = "1.20.0"
lazy_static = "1.5.0"
time = "0.3.37"
maplit = "1.0.2"
priority-queue = "2.1.1"
rand = "0.9.0-beta.1"
